# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:		  [jekyll-paginate, jekyll-gist]
# Permalinks
permalink:        /:categories/:year/:month/:day/:title

# Setup
title:            Nikhil
tagline:          'Entrepreneur, Data Scientist'
description:      'A Physics and Data Science enthusiast. Primarily interested in Business Analytics, Decision Sciences, Non-Linear Dynamical System and Network Sciences.'
url:              http://nikhilkanta.github.io
baseurl:          /

author:
  name:           'Nikhil N Kanta'
  url:            https://nikhilkanta.github.io

paginate:         5

# Custom vars
version:          2.1.0

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-139930508-1

github:           https://github.com/nikhilkanta
repo:             https://github.com/nikhilkanta/nikhilkanta.github.io
